### ISSUE TITLE
when open a modal, use fsm (Ilya's) technique

### ISSUE THREAD

**Issue by MarcGodard** [TxUniverse/tx-base-website#16]

**Comment by MarcGodard** [comment]
@ilyavf this is really old, do you remember what your technique was? I looked through FSM and can't seem to find it.

**Comment by ilyavf** [comment]
@MarcGodard It should look smth like:
```
{{#if isModalVisible}}
    <some-modal />
{{/if}}
```

**Comment by MarcGodard** [comment]
@ilyavf thanks, will do this when I have more time.

**Comment by Paulidis** [comment]
I’m still getting notifications. I’ve tried reaching out a couple times to remove me. I tried muting the threat but I get an error. Can you please manually remove me.

**Comment by MarcGodard** [comment]
@Paulidis you need to stop watching the project. We have no way to stop notifications to you, you control that. Did you even google this? Go to the repo and stop watching it.

**Comment by MarcGodard** [comment]
@ilyavf I tried to do this, however, it caused a bunch of problems. The modal background didn't fade in, the modal size class couldn't be added, and it also changed other styles in the page.

I will close this and keep the current modal setup unless you can tell me why it is worth changing?
